name: Crystal CI

on:
  push:
  pull_request:

jobs:
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: crystal tool format --check

  test:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - name: Install duckdb
        run: curl https://install.duckdb.org | sh
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
